### PR TITLE
fix issue 58

### LINKED ISSUE #58: 熔断功能未生效
**Describe the bug**

在配置中开启熔断功能，触发熔断后，客户端仍能访问到被熔断的实例

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

### PR DESCRIPTION
**Pull request by sak0**
**Please provide issue(s) of this PR:**
Fixes #58 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Config
- [ ] Docs
- [ ] Resolver
- [ ] Performance
- [ ] Monitor and Observability 
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: balancer.go [hunk 1]
```diff
@@ -567,4 +580,50 @@ func (r *resultReporter) report(info balancer.DoneInfo) {
...
+	insRes, err := model.NewInstanceResource(&model.ServiceKey{
+		Namespace: r.namespace,
+		Service:   r.service,
+	}, caller, "http", instance.GetHost(), instance.GetPort())
+	if err != nil {
+		return fmt.Errorf("report circuitBreaker for service %v get instance resource failed: %v",
+			insRes, err)
+	}
+
+	fmt.Printf("report circuitBreaker [%v-%s] for instance %s/%s:%d "+
```
Comment (chuntaojun) [inline balancer.go:608]: 这里 fmt.Printf 不合适吧？

Comment (sak0) [reply balancer.go]: > 这里 fmt.Printf 不合适吧？

已修改

File: balancer.go [hunk 2]
```diff
@@ -567,4 +580,50 @@ func (r *resultReporter) report(info balancer.DoneInfo) {
...
+	caller := &model.ServiceKey{}
+	if r.sourceService != nil {
+		caller.Service = r.sourceService.Service
+		caller.Namespace = r.sourceService.Namespace
+	}
+
+	insRes, err := model.NewInstanceResource(&model.ServiceKey{
+		Namespace: r.namespace,
+		Service:   r.service,
+	}, caller, "http", instance.GetHost(), instance.GetPort())
```
[the remark this answers is not in the document]
Comment (sak0) [reply balancer.go]: > 这个 protocol 应该是 instance.GetProtocol() ? 如果没有默认应该是 grpc？

已修复

**Comment by chuntaojun** [comment]
LGTM
